distro: trusty 

language: python

python: "3.6"

install: 
  - pip install -r backend/requirements.txt
  - npm install -g typescript

script: 
  - pytest
  - sonar-scanner

addons: 
  sonarcloud:
    organization: "three-rocketeers"
