matrix:
  include:
    - language: python
      dist: trusty
      python: '3.6'
      install:
      - pip install -r backend/requirements.txt
      script:
      - pytest
      
    - language: java
      dist: trusty
      jdk: oraclejdk11
      # disable shallow clone so that sonar-scanner has full blame information
      git:
        depth: false
      addons:
        sonarcloud:
          organization: three-rocketeers
      script:
      - npm install typescript
      - sonar-scanner


